### PR TITLE
progress bars: Introduce abstract, linear and radial bars

### LINKED ISSUE #98: QskBusyIndicator
A busy indicator is missing

### PR DESCRIPTION
**Pull request by peter-ha**
Most of the code between linear and radial bars can be shared with a common superclass QskAbstractProgressBar.

Resolves #98

### CODE REVIEW

**Comment by peter-ha** [comment]
[ ] naming ok?
[ ] The original idea of this was to have a modal semitransparent background that blocks the rest; however in F2 or M3 I haven't really seen this. Do we need this?

**Comment by peter-ha** [comment]
Screenshot from 2023-08-04 10-36-08

Screenshot from 2023-08-04 10-36-20

**Comment by peter-ha** [comment]
regarding naming, this is how they are called elsewhere:

- M3: linear progress indicator / circular progress indicator
- F2: progress bar / progress ring
- Clarity (VMWare): progress / spinner
- Decathlon: progress bar / loader
- Goldman Sachs: progress bar / progress circle

I personally find the M3 names best because then we could call the base class QskProgressIndicator. But also QskProgressBar / QskProgressRing or so would be fine...

**Comment by uwerat** [comment]
> regarding naming, this is how they are called elsewhere:
> 
>     * M3: linear progress indicator / circular progress indicator
> 
>     * F2: progress bar / progress ring
> 
>     * Clarity (VMWare): progress / spinner
> 
>     * Decathlon: progress bar / loader
> 
>     * Goldman Sachs: progress bar / progress circle
> 
> 
> I personally find the M3 names best because then we could call the base class QskProgressIndicator. But also QskProgressBar / QskProgressRing or so would be fine...

Please go with Bar/Ring/Indicator

**Comment by peter-ha** [comment]
Renamed the classes as requested.

I also renamed the Bar subcontrol to Fill, because in the indicator/ring case this seems more correct. Also, this makes it consistent with QskSlider.

**Pull request merged**
