### PR TITLE
Don't replace saqt documentation tags

### PR DESCRIPTION
**Pull request by peter-ha**
It is easier for us to parse those special tags in Doxybook, too bad we cannot hook into the tags right in Doxygen.
The current version of the website already contains those commits.

### CODE REVIEW

**Comment by uwerat** [comment]
By simply removing the saqt alias the regular doxygen usage will be broken ?

**Comment by peter-ha** [comment]
> By simply removing the saqt alias the regular doxygen usage will be broken ?

I see, do we need the doxygen-generated web page? In that case I need to check whether I can hack that somehow in doxybook2...

**Comment by uwerat** [comment]
You could do an initial sed editing the Doxfile.

Another option might be to tweak doxyfilter.sh what is registered in Doxyfile. Currently it calls a tiny m4 script, but we could make it configurable by using environment variables ?

**Comment by uwerat** [comment]
Of course doxyfilter.sh currently does not work as it is registered for *.h files only. But of course we can install another filter for *.dox files, that works in a similar way.

**Pull request closed without merging**
